### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-numeral#1]
@kamataryo リリースお願いします。

* 全体的なチェック
* CI のセットアップ & `npm publish` の自動化
* リリース

**Comment by kamataryo** [comment]
@miya0001 対応しました。差分はこちらです。
https://github.com/geolonia/japanese-numeral/compare/baffd9a732dad2761b954d05c63e2efafc834e12..master

- 全体的なチェック => 特に気になるところ無し
- パッケージページ => https://www.npmjs.com/package/@geolonia/japanese-numeral
- リリース後に型補完が利くことを確認済みです
