### ISSUE TITLE
number2kanjiで、0は空の文字

### ISSUE THREAD

**Issue by mikihiro-t** [geolonia/japanese-numeral#17]
`console.log(japaneseNum.kanji2number('〇')) // 0`

`console.log(japaneseNum.number2kanji(0)) //空の文字が返る`

と異なるのは仕様でしょうか？

[normalize-japanese-addresses](https://github.com/geolonia/normalize-japanese-addresses)を、C#に移植中で、移植できたら公開予定ですが、TypeScriptはビギナーなのでなかなか難しく・・・。

**Comment by kamataryo** [comment]
@mikihiro-t こんにちは、Issue を作成いただきありがとうございます！
@geolonia/japanese-numeral@1.0.1 で `0` -> `''` と変換されるのは本バージョンの仕様ではありますが、実装における考慮漏れのように思われ、おっしゃる通りに変換されるのがライブラリの動作としてより適切だと現在のところ考えています。
japanese-numeral のバージョンアップとして #18 で改修を試みています。
改修やリリースの経緯を引き続きこのスレッドでご連絡させていただければと思います。

C# への normalize-japanese-addresses (NJA) への移植を行っているとのこと、素晴らしいプロジェクトですね。ぜひ完成の暁には詳細教えていただけますと嬉しいです。NJA や関連ライブラリの動作にご不明な点などがありましたら issue などで質問いただくこといつでも歓迎です。

**Comment by kamataryo** [comment]
@mikihiro-t こんにちは、`japaneseNum.number2kanji(0) === '〇' // true` となる変更を #18 で追加して取り込み、@geolonia/japanese-numeral@1.0.2` としてリリースしましたのでお知らせします。

また何かご不明な点や気になる点などありましたら、ぜひお気軽にコメントいただければと思います。
この度はありがとうございました！

**Comment by mikihiro-t** [comment]
改修ありがとうございました。また質問することがあると思いますので、よろしくお願いします。
