### ISSUE TITLE
findKanjiNumbersで、旧字体の「壱」を検出できない

### ISSUE THREAD

**Issue by naogify** [geolonia/japanese-numeral#7]
```
const test = findKanjiNumbers("壱番クジを引きました");
console.log(test)
```

とすると空の配列が返ってくる。

参考
https://codesandbox.io/s/affectionate-sun-kz3k8?file=/src/index.js

**Comment by miya0001** [comment]
以下に旧字体のリストがあるので、それを正規表現に入れる感じですかね。
https://github.com/geolonia/japanese-numeral/blob/master/src/oldJapaneseNumerics.ts
